const router = require("express").Router()
const homeCtrl = require("../modules/home/home.controller")
const authCtrl = require("../modules/auth/auth.controller")
const auth = require("../middleware/auth.middleware")
const authRouter = require("../modules/auth/auth.router")
const homeRouter = require("../modules/home/home.router")
const brandRouter = require("../modules/brand/brand.router")
const categoryRouter = require("../modules/category/category.router")
const userRouter = require("../modules/user/user.router")
const productRouter = require("../modules/products/product.router")
const orderDetailRouter = require("../modules/order-detail/order-detail.router")
const orderRouter = require("../modules/order/order.router")
const chatRouter = require("../modules/chat/chat.router")
const couponRouter = require("../modules/coupon/coupon.router")
const bannerRouter = require("../modules/banner/banner.router")


router.use(homeRouter)
router.use('/auth', authRouter)
router.use("/brand", brandRouter)
router.use("/category", categoryRouter) 
router.use('/user', userRouter) 
router.use('/product', productRouter)
router.use('/order-detail', orderDetailRouter) 
router.use('/order', orderRouter)
router.use('/chat', chatRouter)
router.use('/coupon', couponRouter)
router.use('/banner', bannerRouter)

module.exports = router; 
